apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: server
        image: nginx:1.27 # Placeholder image
